### ISSUE TITLE
Sampling all raised some exceptions

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#111]
Here are some exceptions during the sampling all:
http://aws-spark-quoll-1.ala:9194/job/Sample%20all%20datasets/1/consoleFull

Here are the exceptions:
```
...
20/07/29 08:46:15 [dr807] 1  WARN SourceRDD$Bounded: Failed to get estimated bundle size for source hdfs://aws-spark-quoll-1.ala:9000/pipelines-data/dr807/1/interpreted/location/interpret-*.avro, using default bundle size of 67108864 bytes.
20/07/29 08:46:15 [dr807] 1  INFO AbstractConnector: Stopped Spark@6b25ef1c{HTTP/1.1,[http/1.1]}{172.30.1.102:4040}
Exception in thread "main" java.lang.RuntimeException: Failed to create partitions for source AvroSource
	at org.apache.beam.runners.spark.io.SourceRDD$Bounded.getPartitions(SourceRDD.java:123)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:273)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:269)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
	at org.apache.spark.SparkContext$$anonfun$union$1$$anonfun$31.apply(SparkContext.scala:1314)
	at org.apache.spark.SparkContext$$anonfun$union$1$$anonfun$31.apply(SparkContext.scala:1314)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.apache.spark.SparkContext$$anonfun$union$1.apply(SparkContext.scala:1314)
	at org.apache.spark.SparkContext$$anonfun$union$1.apply(SparkContext.scala:1313)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.SparkContext.withScope(SparkContext.scala:699)
	at org.apache.spark.SparkContext.union(SparkContext.scala:1313)
	at org.apache.spark.api.java.JavaSparkContext.union(JavaSparkContext.scala:514)
	at org.apache.spark.api.java.JavaSparkContextVarargsWorkaround.union(JavaSparkContextVarargsWorkaround.java:36)
	at org.apache.beam.runners.spark.translation.TransformTranslator$1.evaluate(TransformTranslator.java:101)
	at org.apache.beam.runners.spark.translation.TransformTranslator$1.evaluate(TransformTranslator.java:81)
	at org.apache.beam.runners.spark.SparkRunner$Evaluator.doVisitTransform(SparkRunner.java:430)
	at org.apache.beam.runners.spark.SparkRunner$Evaluator.visitPrimitiveTransform(SparkRunner.java:419)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:665)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:657)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:657)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$600(TransformHierarchy.java:317)
	at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:251)
	at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:460)
	at org.apache.beam.runners.spark.SparkRunner.lambda$run$1(SparkRunner.java:225)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: No files matched spec: hdfs://aws-spark-quoll-1.ala:9000/pipelines-data/dr807/1/interpreted/location/interpret-*.avro
	at org.apache.beam.sdk.io.FileSystems.maybeAdjustEmptyMatchResult(FileSystems.java:167)
	at org.apache.beam.sdk.io.FileSystems.match(FileSystems.java:154)
	at org.apache.beam.sdk.io.FileBasedSource.split(FileBasedSource.java:262)
	at org.apache.beam.runners.spark.io.SourceRDD$Bounded.getPartitions(SourceRDD.java:115)
	... 65 more
Dataset = dr7437 and count = 79717
...
...
...
Exception in thread "main" java.lang.RuntimeException: Sampling directory cant be found. Has sampling from spatial-service been ran ? Missing dir: hdfs://aws-spark-quoll-1.ala:9000/pipelines-data/dr807/1/sampling/downloads
	at au.org.ala.pipelines.beam.ALASamplingToAvroPipeline.getColumnHeaders(ALASamplingToAvroPipeline.java:201)
	at au.org.ala.pipelines.beam.ALASamplingToAvroPipeline.run(ALASamplingToAvroPipeline.java:68)
	at au.org.ala.pipelines.beam.ALASamplingToAvroPipeline.main(ALASamplingToAvroPipeline.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Wed Jul 29 15:46:46 AEST 2020
Adding sampling to dr807 took 0 minutes and 4 seconds.
...
...
...
20/07/29 17:10:25 []   WARN DFSClient: Caught exception 
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1252)
	at java.lang.Thread.join(Thread.java:1326)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeResponder(DFSOutputStream.java:969)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.endBlock(DFSOutputStream.java:707)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:896)
20/07/29 17:10:25 []   INFO AbstractConnector: Stopped Spark@38c761e9{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
...
```

**Comment by djtfmartin** [comment]
The sampling failed for two datasets: **dr807** and **dr153**.

The sampling failed for **dr807** because interpretation had not ran successfully. 
This is because the `connectionParameters` for **dr807** specifies 2 URLs - and the code was assuming this was a single property:

```json
"connectionParameters": {
"csv_escape_char": "~",
"protocol": "DwC",
"automation": false,
"strip": false,
"csv_eol": "\n",
"csv_text_enclosure": "\"",
"csv_delimiter": ",",
"incremental": false,
"url": [
"http://......",
"http://......"
]
}
```

**Comment by djtfmartin** [comment]
I cant reproduce the error with `dr153`. Im going to move this Review as the work for the other issue is done and awaiting review.
