### ISSUE TITLE
Interpretation for dr807 fails - Multiple URL values

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#113]
The following exception is thrown for dr807

```
Caused by: j213.com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (o115.okhttp3.ResponseBody$BomAwareReader); line: 1, column: 1558] (through reference chain: au.org.ala.kvs.client.ALACollectoryMetadata$ALACollectoryMetadataBuilder["connectionParameters"]->au.org.ala.kvs.client.ConnectionParameters$ConnectionParametersBuilder["url"])
	at j213.com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at j213.com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468)
	at j213.com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242)
	at j213.com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:720)
	at j213.com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:40)
	at j213.com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at j213.com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
	at j213.com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:274)
	at j213.com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:198)
	at j213.com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
	at j213.com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:274)
	at j213.com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:198)
	at j213.com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2057)
	at j213.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1463)
	at r240.retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at r240.retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at r240.retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at r240.retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at org.gbif.rest.client.retrofit.SyncCall.syncCall(SyncCall.java:34)
```

This is because the DTO for `ConnectionParameters` only supports a single string.

Related to #111

**Comment by djtfmartin** [comment]
Fixed in https://github.com/gbif/pipelines/pull/358
