### ISSUE TITLE
UnsupportedArchiveException: DwC-A data file »image.csv« does not exist

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#130]
The latest exports contain an image extension in the meta.xml, but the image.csv file is always provided.
This causes the following exception to be thrown by `DwcaToVerbatimPipeline`

```
Caused by: org.gbif.dwc.UnsupportedArchiveException: DwC-A data file »image.csv« does not exist
	at org.gbif.dwc.ArchiveFile.validate(ArchiveFile.java:127)
	at org.gbif.dwc.ArchiveFile.validateAsExtension(ArchiveFile.java:116)
	at org.gbif.dwc.Archive.validate(Archive.java:150)
	at org.gbif.dwc.DwcFiles.fromCompressed(DwcFiles.java:62)
	at org.gbif.pipelines.core.io.DwcaReader.fromCompressed(DwcaReader.java:37)
	at org.gbif.pipelines.common.beam.DwcaIO$BoundedDwCAReader.start(DwcaIO.java:154)
	at org.apache.beam.runners.spark.io.SourceRDD$Bounded$ReaderToIteratorAdapter.seekNext(SourceRDD.java:213)
	at org.apache.beam.runners.spark.io.SourceRDD$Bounded$ReaderToIteratorAdapter.tryProduceNext(SourceRDD.java:186)

``` 

Could be fixed by optionally adding the extension or always including the image.csv file, even if its a blank file.

**Comment by djtfmartin** [comment]
This can be closed as @sadeghim has fixed it.

**Comment by javier-molina** [comment]
This was a bug for #103
