### ISSUE TITLE
TemporalParserTest fail on systems with a Locale different than English

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/la-pipelines#189]
In my development environment (with locale `es_ES`) these tests fails:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.gbif.pipelines.parsers.config.factory.ConfigFactoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.236 sec - in org.gbif.pipelines.parsers.config.factory.ConfigFactoryTest
Running org.gbif.pipelines.parsers.parsers.temporal.TemporalParserTest
Tests run: 74, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.189 sec <<< FAILURE! - in org.gbif.pipelines.parsers.parsers.temporal.TemporalParserTest
localDateTextMonthFirstCommaTest(org.gbif.pipelines.parsers.parsers.temporal.TemporalParserTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1999-04-01> but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.gbif.pipelines.parsers.parsers.temporal.TemporalParserTest.localDateTextMonthFirstCommaTest(TemporalParserTest.java:775)

localDateTextMonthFirstTest(org.gbif.pipelines.parsers.parsers.temporal.TemporalParserTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1999-04-01> but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.gbif.pipelines.parsers.parsers.temporal.TemporalParserTest.localDateTextMonthFirstTest(TemporalParserTest.java:970)
```

And work running tests with: 
```
LANG=en_US.UTF-8 .buildSrc/mvnw test 
```
In the past we had similar issues with server locales different than English: AtlasOfLivingAustralia/biocache-service#417 

I'll send a PR to fix this.

**Comment by vjrj** [comment]
This is fixed after the gbif-ala-dev merge, closing it.
