### ISSUE TITLE
Exceptions in validation when data resource not available in collectory

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#220]
When a data resource has been removed from the collectory, the webservice URL to retrieve metadata returns a 500 (should be a `400` or `404`).

Pipelines should fail the validation in this event which will halt downstream processes for a dataset.

Exception thrown

```15-Dec 07:20:02 [UUID] [dr2230] [ERROR] ALAAttributionKVStoreFactory: Unable to connect to http service
r240.retrofit2.HttpException: HTTP 500 
	at org.gbif.rest.client.retrofit.SyncCall.syncCall(SyncCall.java:39)
	at au.org.ala.kvs.client.retrofit.ALACollectoryServiceClient.lookupDataResource(ALACollectoryServiceClient.java:40)
	at au.org.ala.kvs.cache.ALAAttributionKVStoreFactory$1.get(ALAAttributionKVStoreFactory.java:62)
	at au.org.ala.kvs.cache.ALAAttributionKVStoreFactory$1.get(ALAAttributionKVStoreFactory.java:58)
	at org.cache2k.core.InternalCache2kBuilder$2.load(InternalCache2kBuilder.java:125)
	at org.cache2k.core.HeapCache.load(HeapCache.java:1363)
	at org.cache2k.core.HeapCache.getEntryInternal(HeapCache.java:652)
	at org.cache2k.core.HeapCache.getEntryInternal(HeapCache.java:624)
	at org.cache2k.core.HeapCache.get(HeapCache.java:548)
	at org.gbif.kvs.cache.KeyValueCache.get(KeyValueCache.java:59)
	at au.org.ala.pipelines.beam.ALAUUIDValidationPipeline.run(ALAUUIDValidationPipeline.java:87)
	at au.org.ala.pipelines.beam.ALAUUIDMintingPipeline.run(ALAUUIDMintingPipeline.java:104)
	at au.org.ala.pipelines.beam.ALAUUIDMintingPipeline.main(ALAUUIDMintingPipeline.java:92)
Exception in thread "main" org.cache2k.integration.CacheLoaderException: java.lang.RuntimeException: r240.retrofit2.HttpException: HTTP 500 
	at org.cache2k.core.StandardExceptionPropagator.propagateException(StandardExceptionPropagator.java:48)
	at org.cache2k.core.HeapCache.returnValue(HeapCache.java:1256)
	at org.cache2k.core.HeapCache.get(HeapCache.java:552)
	at org.gbif.kvs.cache.KeyValueCache.get(KeyValueCache.java:59)
	at au.org.ala.pipelines.beam.ALAUUIDValidationPipeline.run(ALAUUIDValidationPipeline.java:87)
	at au.org.ala.pipelines.beam.ALAUUIDMintingPipeline.run(ALAUUIDMintingPipeline.java:104)
	at au.org.ala.pipelines.beam.ALAUUIDMintingPipeline.main(ALAUUIDMintingPipeline.java:92)
Caused by: java.lang.RuntimeException: r240.retrofit2.HttpException: HTTP 500 
	at au.org.ala.kvs.cache.ALAAttributionKVStoreFactory.logAndThrow(ALAAttributionKVStoreFactory.java:98)
	at au.org.ala.kvs.cache.ALAAttributionKVStoreFactory.access$000(ALAAttributionKVStoreFactory.java:15)
	at au.org.ala.kvs.cache.ALAAttributionKVStoreFactory$1.get(ALAAttributionKVStoreFactory.java:66)
	at au.org.ala.kvs.cache.ALAAttributionKVStoreFactory$1.get(ALAAttributionKVStoreFactory.java:58)
	at org.cache2k.core.InternalCache2kBuilder$2.load(InternalCache2kBuilder.java:125)
	at org.cache2k.core.HeapCache.load(HeapCache.java:1363)
	at org.cache2k.core.HeapCache.getEntryInternal(HeapCache.java:652)
	at org.cache2k.core.HeapCache.getEntryInternal(HeapCache.java:624)
	at org.cache2k.core.HeapCache.get(HeapCache.java:548)
	... 4 more
```

**Comment by djtfmartin** [comment]
There is a workaround included in https://github.com/gbif/pipelines/pull/460.
