### ISSUE TITLE
Intermittent errors when running interpretation for certain datasets (dr359)

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#222]
When processing some of the larger datasets on the cluster, the following messages  are logged :

```
21/01/06 23:23:14 [VERBATIM_TO_INTERPRETED] [dr359] ERROR TaskSchedulerImpl: Lost executor 6 on 172.30.1.43: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
21/01/06 23:25:10 [VERBATIM_TO_INTERPRETED] [dr359] ERROR TaskSchedulerImpl: Lost executor 7 on 172.30.1.43: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
21/01/06 23:30:23 [VERBATIM_TO_INTERPRETED] [dr359] ERROR TaskSchedulerImpl: Lost executor 18 on 172.30.1.43: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
21/01/06 23:31:56 [VERBATIM_TO_INTERPRETED] [dr359] ERROR TaskSchedulerImpl: Lost executor 8 on 172.30.1.43: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
```

followed by this exception

```
21/01/06 23:31:56 [VERBATIM_TO_INTERPRETED] [dr359] INFO AbstractConnector: Stopped Spark@1e965426{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
Exception in thread "main" java.lang.RuntimeException: org.apache.spark.SparkException: Job aborted due to stage failure: ShuffleMapStage 32 (flatMapToPair at GroupNonMergingWindowsFunctions.java:115) has failed the maximum allowable number of times: 4. Most recent failure reason: org.apache.spark.shuffle.MetadataFetchFailedException: Missing an output location for shuffle 2 	at org.apache.spark.MapOutputTracker$$anonfun$convertMapStatuses$2.apply(MapOutputTracker.scala:882) 	at org.apache.spark.MapOutputTracker$$anonfun$convertMapStatuses$2.apply(MapOutputTracker.scala:878) 	at scala.collection.Iterator$class.foreach(Iterator.scala:891) 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) 	at org.apache.spark.MapOutputTracker$.convertMapStatuses(MapOutputTracker.scala:878) 	at org.apache.spark.MapOutputTrackerWorker.getMapSizesByExecutorId(MapOutputTracker.scala:691) 	at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala:49) 	at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:105) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:359) 	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:357) 	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165) 	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156) 	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091) 	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156) 	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882) 	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:357) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:308) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:359) 	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:357) 	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165) 	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156) 	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091) 	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156) 	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882) 	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:357) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:308) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99) 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55) 	at org.apache.spark.scheduler.Task.run(Task.scala:123) 	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408) 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360) 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) 
	at org.apache.beam.runners.spark.SparkPipelineResult.runtimeExceptionFrom(SparkPipelineResult.java:58)
	at org.apache.beam.runners.spark.SparkPipelineResult.beamExceptionFrom(SparkPipelineResult.java:75)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:102)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:90)
	at au.org.ala.pipelines.beam.ALAVerbatimToInterpretedPipeline.run(ALAVerbatimToInterpretedPipeline.java:287)
	at au.org.ala.pipelines.beam.ALAVerbatimToInterpretedPipeline.main(ALAVerbatimToInterpretedPipeline.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```	

There 3 workarounds for this issue:

1) Shutdown the spark slave on aws-spark-quoll-1b - no errors logged, but interpretation takes longer to execute.
2) Reduce the number of workers on aws-spark-quoll-1b (to 16 or less)
3) Increase the ` spark.default.parallelism` value in `/data/la-pipelines/config/la-pipelines-local.yaml like so:

```
interpret-sh-args:
  spark-cluster:
    conf: spark.default.parallelism=500
```    
The job completes successfully with these settings but there are still errors like 

```
21/01/07 01:19:46 [VERBATIM_TO_INTERPRETED] [dr359] ERROR TaskSchedulerImpl: Lost executor 8 on 172.30.1.43: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
```
 
The proper fix is to implement #132 which will involve moving the HDFS name node to a separate VM.
I cant see there is anything to action here until #132 is tackled.

**Comment by djtfmartin** [comment]
Reducing the number of workers on **aws-spark-quoll-1b** (to 16 compared to 24 on other nodes), helps reduce the load on master so that interpretation completes without the `Likely due to containers exceeding thresholds` messages.

**Comment by djtfmartin** [comment]
Im not seeing this problem after #232. This can be closed
