### ISSUE TITLE
Problems with SOLR 8.8

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#244]
I upgraded the cluster to 8.8.0 and hit the following errors:

```
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.io.IOException: Error writing to Solr after 9 attempt(s). No more attempts allowed
	at org.apache.beam.runners.spark.SparkPipelineResult.beamExceptionFrom(SparkPipelineResult.java:69)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:102)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:90)
	at au.org.ala.pipelines.beam.IndexRecordToSolrPipeline.run(IndexRecordToSolrPipeline.java:145)
	at au.org.ala.pipelines.beam.IndexRecordToSolrPipeline.main(IndexRecordToSolrPipeline.java:50)
Caused by: java.io.IOException: Error writing to Solr after 9 attempt(s). No more attempts allowed
	at org.apache.beam.sdk.io.solr.SolrIO$Write$WriteFn.flushBatch(SolrIO.java:681)
	at org.apache.beam.sdk.io.solr.SolrIO$Write$WriteFn.processElement(SolrIO.java:643)
Caused by: org.apache.solr.client.solrj.SolrServerException: java.lang.NullPointerException
	at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:983)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:827)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.beam.sdk.io.solr.AuthorizedSolrClient.process(AuthorizedSolrClient.java:65)
	at org.apache.beam.sdk.io.solr.SolrIO$Write$WriteFn.flushBatch(SolrIO.java:667)
	at org.apache.beam.sdk.io.solr.SolrIO$Write$WriteFn.processElement(SolrIO.java:643)
	at org.apache.beam.sdk.io.solr.SolrIO$Write$WriteFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:227)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:186)
	at org.apache.beam.runners.spark.translation.DoFnRunnerWithMetrics.processElement(DoFnRunnerWithMetrics.java:65)
	at org.apache.beam.runners.spark.translation.SparkProcessContext$ProcCtxtIterator.computeNext(SparkProcessContext.java:137)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$27.apply(RDD.scala:972)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$27.apply(RDD.scala:972)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.apache.solr.common.cloud.ZkCoreNodeProps.getCoreUrl(ZkCoreNodeProps.java:53)
	at org.apache.solr.common.cloud.ZkCoreNodeProps.getCoreUrl(ZkCoreNodeProps.java:27)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.buildUrlMap(CloudSolrClient.java:727)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.directUpdate(CloudSolrClient.java:602)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1002)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:891)
	... 29 more
```

Rolling back to 8.7.0 fixed this issue, so I'm associating the problem with this current release and perhaps compatitiblilty with our current version of apache beam.

Nothing currently to action here. This can stay in the backlog and be used as a reference for testing further versions of SOLR. 	
This has been noted on the SOLR downloads page:

```Client applications that use a SolrJ version prior to 8.8.0 may experience a NullPointerException in ZkCoreNodeProps when requesting cluster state from Zookeeper. Upgrading your application to use SolrJ 8.8.0 will fix the issue.```

**Comment by djtfmartin** [comment]
The problems are fixed in 8.8.1. This is now deployed to our dev environment.
