### ISSUE TITLE
Problem recognising projection EPSG:4938 - seen with dataset dr343

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#269]
```
	... 23 more
27-Feb 09:31:00 [VERBATIM_TO_INTERPRETED] [dr343] [WARN] Wgs84Projection: Coordinate re-projection failed for datum EPSG:4938, lat -23.7 and lon 133.866667: No transformation available from system "CartesianCS[Earth centred, earth fixed, righthanded 3D coordinate system, consisting of 3 (...) positive Z-axis parallel to mean earth rotation axis and pointing towards North Pole. UoM: m.]" to "CartesianCS[Geocentric]".
org.opengis.referencing.operation.OperationNotFoundException: No transformation available from system "CartesianCS[Earth centred, earth fixed, righthanded 3D coordinate system, consisting of 3 (...) positive Z-axis parallel to mean earth rotation axis and pointing towards North Pole. UoM: m.]" to "CartesianCS[Geocentric]".
	at org.geotools.referencing.operation.AbstractCoordinateOperationFactory.swapAndScaleAxis(AbstractCoordinateOperationFactory.java:273)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.createOperationStep(DefaultCoordinateOperationFactory.java:1232)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.createOperationStep(DefaultCoordinateOperationFactory.java:1317)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.findOperations(DefaultCoordinateOperationFactory.java:368)
	at org.geotools.referencing.operation.DefaultCoordinateOperationFactory.createOperation(DefaultCoordinateOperationFactory.java:213)
	at org.geotools.referencing.operation.BufferedCoordinateOperationFactory.createOperation(BufferedCoordinateOperationFactory.java:234)
	at org.geotools.referencing.CRS.findMathTransform(CRS.java:1260)
	at org.gbif.pipelines.core.parsers.location.parser.Wgs84Projection.reproject(Wgs84Projection.java:77)
	at au.org.ala.pipelines.parser.CoordinatesParser.parseCoords(CoordinatesParser.java:91)
	at au.org.ala.pipelines.interpreters.ALALocationInterpreter.lambda$interpretStateProvince$1(ALALocationInterpreter.java:88)
	at org.gbif.pipelines.core.interpreters.Interpretation$Handler.lambda$via$0(Interpretation.java:95)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.gbif.pipelines.core.interpreters.Interpretation$Handler.via(Interpretation.java:95)
	at au.org.ala.pipelines.transforms.LocationTransform.processElement(LocationTransform.java:170)
	at au.org.ala.pipelines.java.ALAVerbatimToInterpretedPipeline.lambda$run$1(ALAVerbatimToInterpretedPipeline.java:336)
	at au.org.ala.pipelines.java.ALAVerbatimToInterpretedPipeline.lambda$run$6(ALAVerbatimToInterpretedPipeline.java:367)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.IllegalArgumentException: No source axis match OTHER.
	at org.geotools.referencing.operation.matrix.GeneralMatrix.<init>(GeneralMatrix.java:347)
	at org.geotools.referencing.operation.matrix.GeneralMatrix.<init>(GeneralMatrix.java:251)
	at org.geotools.referencing.cs.AbstractCS.swapAndScaleAxis(AbstractCS.java:323)
	at org.geotools.referencing.operation.AbstractCoordinateOperationFactory.swapAndScaleAxis(AbstractCoordinateOperationFactory.java:271)
	... 21 more
```

**Comment by javier-molina** [comment]
@djtfmartin is this a data issue or yet to be determined?

**Comment by javier-molina** [comment]
Check with @peggynewman

**Comment by javier-molina** [comment]
@djtfmartin do you know if this is still an issue?

**Comment by peggynewman** [comment]
The dataset is available in prod now
202,766/229,051 records have `Geodetic datum assumed WGS84`

https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr343&fq=assertions:GEODETIC_DATUM_ASSUMED_WGS84
