### ISSUE TITLE
ImageSync timeout

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#434]
Seen in Jenkins for `ImageServiceSyncPipeline` for dr1411 (iNat)

```
Exception in thread "main" org.gbif.rest.client.retrofit.RestClientException: Error executing call
	at org.gbif.rest.client.retrofit.SyncCall.syncCall(SyncCall.java:42)
	at au.org.ala.pipelines.beam.ImageServiceSyncPipeline.downloadImageMapping(ImageServiceSyncPipeline.java:405)
	at au.org.ala.pipelines.beam.ImageServiceSyncPipeline.run(ImageServiceSyncPipeline.java:117)
	at au.org.ala.pipelines.beam.ImageServiceSyncPipeline.main(ImageServiceSyncPipeline.java:72)
Caused by: java.net.SocketTimeoutException: timeout
	at o115.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
	at o115.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
	at o115.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
	at o115.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
	at o115.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at o115.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at o115.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at o115.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at o115.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at o115.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at o115.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at o115.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at o115.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at o115.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at o115.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at au.org.ala.utils.WsUtils.lambda$createOKClient$0(WsUtils.java:86)
	at o115.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at o115.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at o115.okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at r240.retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at org.gbif.rest.client.retrofit.SyncCall.syncCall(SyncCall.java:35)
	... 3 more
```

Should be possible to fix in config in `la-pipelines.yaml` by increasing the timeout

```
imageService:
  wsUrl: https://images-test.ala.org.au/
  timeoutSec: 180
```

**Comment by djtfmartin** [comment]
Seems to be fixed with the timeout settings.

**Comment by djtfmartin** [comment]
This happened again today. First thought is that the image-service export is blocked when existing batch AVRO uploads are running. Only affecting `dr1411` - the largest image dataset.

cc @sbearcsiro

**Comment by patkyn** [comment]
FYI, we're experiencing the same issue from the latest inaturalist load http://aws-spark-quoll-master.ala:9194/job/Image-sync/293/console. 

![image](https://user-images.githubusercontent.com/1606595/123575352-e5b93d80-d814-11eb-9016-db6592a3476e.png)

**Comment by sbearcsiro** [comment]
This is caused by the time taken to run the export_dataset_mapping SQL on the image service, see this excerpt from the postgres log (which has been configured to log slow queries):
```
2021-06-28 12:24:37.928 AEST [3947289] images@images LOG:  duration: 185022.174 ms  execute <unnamed>/C_8: select * from export_dataset($1)
2021-06-28 12:24:37.928 AEST [3947289] images@images DETAIL:  parameters: $1 = 'dr1411'```

This one was approximately 5 seconds too slow for the read timeout of the HTTP client above (not including any overhead added by Grails.

I expect this is caused by load on the image-service server and probably specifically on load in the postgresql service.

Running `explain` on the query behind the function that backs `export_dataset`:
```
                             QUERY PLAN                              
---------------------------------------------------------------------
 Seq Scan on image i  (cost=0.00..1538538.45 rows=3688527 width=485)
   Filter: ((data_resource_uid)::text = 'dr1411'::text)```

So even with the index on the data_resource_uid column the 3.6M rows under dr1411 causes it to use a sequence scan.  Running the same explain on a smaller data_resource_uid, eg `dr101` shows it running an index scan in place of the seq scan above.

When I was running this, `select * from export_dataset('dr1411');` in `psql` returned in

```Time: 148724.183 ms (02:28.724)```

At the time, the load average on the server was in the 2.5-3 range.  While this time is within the read timeout of the pipelines HTTP client in this example presumably it wouldn't take much additional load on the server to push it over the threshold.

I would suggest adding an either an exponential backoff retry to the HTTP call or additional read timeout buffer to cover these high load periods (or maybe both).

**Comment by djtfmartin** [comment]
PR merged here: https://github.com/AtlasOfLivingAustralia/image-service/pull/159

**Comment by djtfmartin** [comment]
Test, and deployed to production.
Works well in production.

**Comment by djtfmartin** [comment]
There where issues with this in production and it was rolled back.

Now working well in test environment with version 1.1.7.1 of image-service
