### ISSUE TITLE
 multiple values encountered for non multiValued field dynamicProperties_mapSheetNumber

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#440]
```
ERROR: [doc=011de67b-7183-4772-b868-74f0f93ffa6b] multiple values encountered for non multiValued field dynamicProperties_mapSheetNumber: [Valid and accepted without modification, 9029 - WOLLONGONG]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:577)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:372)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:325)
	at org.apache.solr.client.solrj.impl.CloudSolrClient$2.call(CloudSolrClient.java:628)
	at org.apache.solr.client.solrj.impl.CloudSolrClient$2.call(CloudSolrClient.java:625)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$1.run(ExecutorUtil.java:231)
	... 3 more
````

**Comment by djtfmartin** [comment]
PR here: https://github.com/gbif/pipelines/pull/551

**Comment by javier-molina** [comment]
@charvolant when you have a chance can you please confirm that the impacted DR(s) are now working?

**Comment by javier-molina** [comment]
Latest update from Doug:

> @Dave Martin (ALA) There’s still something not quite right. https://biocache.ala.org.au/occurrences/search?q=dynamicProperties_mapSheetNumber%3A*&fq=data_resource_uid:dr368&qualityProfile=ALA&disableAllQualityFilters=true shows 11014 records, doing unzip -p dr368.zip occurrence.csv | grep '""mapSheetNumber"":""[0-9]' | wc -l gives a count of 11004895

**Comment by djtfmartin** [comment]
Theres only 41,995 values for `mapSheetNumber` supplied, the rest are null. This corresponds with the number of indexed values in biocache service.

```
spark.sqlContext.sql("CREATE TEMPORARY VIEW VERBATIM USING avro OPTIONS (path \"hdfs://aws-spark-quoll-master.ala:9000/pipelines-data/dr368/1/verbatim.avro\")")
scala> spark.sqlContext.sql("select count(*)  from VERBATIM where coreTerms.`http://unknown.org/mapSheetNumber` is not null").show(false);
+--------+                                                                      
|count(1)|
+--------+
|41995   |
+--------+

```

This can be closed.
