### ISSUE TITLE
interpretation error during name matching

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#492]
See the console log here:
http://aws-spark-quoll-master.ala:9194/job/Interpret-dataset/2441/console
```
...
Caused by: au.org.ala.ws.ClientException: Unable to contact service for r240.retrofit2.OkHttpCall@16ee7a2c
	at au.org.ala.names.ws.client.ALANameUsageMatchServiceClient.call(ALANameUsageMatchServiceClient.java:168)
	at au.org.ala.names.ws.client.ALANameUsageMatchServiceClient.check(ALANameUsageMatchServiceClient.java:119)
	at au.org.ala.kvs.cache.ALANameCheckKVStoreFactory$1.get(ALANameCheckKVStoreFactory.java:84)
	... 64 more
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:9179
	at o115.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at o115.okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at o115.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at o115.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at o115.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at o115.okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at o115.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
...
```

**Comment by djtfmartin** [comment]
@sadeghim can this be closed ? I think we restarted docker services and this fixed the issue

**Comment by djtfmartin** [comment]
Closing as i think this is resolved.
