### ISSUE TITLE
Databox  - `dwca-avro` problem - SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] 

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#518]
```
[mException in thread "main" org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Linux and os.arch=aarch64
	at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:299)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:163)
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:145)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:81)
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:68)
	at org.apache.beam.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:54)
	at org.apache.beam.sdk.util.SerializableUtils.clone(SerializableUtils.java:117)
	at org.apache.beam.sdk.util.SerializableUtils.ensureSerializable(SerializableUtils.java:96)
	at org.apache.beam.sdk.io.Read$Bounded.<init>(Read.java:138)
	at org.apache.beam.sdk.io.Read$Bounded.<init>(Read.java:133)
	at org.apache.beam.sdk.io.Read.from(Read.java:96)
	at org.gbif.pipelines.common.beam.DwcaIO$Read.expand(DwcaIO.java:93)
	at org.gbif.pipelines.common.beam.DwcaIO$Read.expand(DwcaIO.java:43)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499)
	at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:56)
	at org.apache.beam.sdk.Pipeline.apply(Pipeline.java:192)
	at au.org.ala.pipelines.beam.ALADwcaToVerbatimPipeline.run(ALADwcaToVerbatimPipeline.java:123)
	at au.org.ala.pipelines.beam.ALADwcaToVerbatimPipeline.runWithLocking(ALADwcaToVerbatimPipeline.java:53)
	at au.org.ala.pipelines.beam.ALADwcaToVerbatimPipeline.main(ALADwcaToVerbatimPipeline.java:38)
	
```

**Comment by djtfmartin** [comment]
This is now fixed.
